import { useEffect, useState } from "react"
import { collection, query, where, getDocs } from "firebase/firestore"
import { db }       from "../../config/firebase"
import { useAuth }  from "../../context/AuthContext"
import PortalLayout from "../../components/layout/PortalLayout"
import Card         from "../../components/ui/Card"
import Badge        from "../../components/ui/Badge"
import SectionTag   from "../../components/ui/SectionTag"
import Button       from "../../components/ui/Button"

export default function Reports() {
  const { user }              = useAuth()
  const [reports, setReports] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (!user) return
    const fetch = async () => {
      const snap = await getDocs(
        query(collection(db, "reports"), where("clientUid", "==", user.uid))
      )
      setReports(snap.docs.map(d => ({ id: d.id, ...d.data() })))
      setLoading(false)
    }
    fetch()
  }, [user])

  if (loading) return (
    <PortalLayout title="Reports">
      <div className="flex items-center justify-center h-64">
        <p className="font-mono text-xs text-dim animate-pulse tracking-widest">LOADING...</p>
      </div>
    </PortalLayout>
  )

  return (
    <PortalLayout title="Reports">
      <SectionTag text="Your Reports" />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-4">
        {reports.length === 0 ? (
          <Card>
            <p className="font-mono text-xs text-dim">
              No reports available yet. Reports will appear here once
              your engagement is complete.
            </p>
          </Card>
        ) : reports.map(r => (
          <Card key={r.id}>
            {/* Icon */}
            <div className="text-3xl mb-4">
              {r.type === "technical" ? "🔧" : "📊"}
            </div>

            {/* Title */}
            <h3 className="font-orbitron font-bold text-base mb-2">
              {r.engagementTitle || "Engagement Report"}
            </h3>

            {/* Meta */}
            <div className="flex items-center gap-4 mb-4">
              <Badge
                label={r.type === "technical" ? "Technical" : "Executive"}
                type={r.type === "technical" ? "team" : "client"}
              />
              <span className="font-mono text-xs text-dim">
                {r.createdAt?.toDate?.()?.toLocaleDateString() || "—"}
              </span>
            </div>

            <p className="font-mono text-xs text-dim leading-relaxed mb-6">
              {r.type === "technical"
                ? "Full technical report including all findings, CVSS scores, proof of concepts, and detailed remediation steps."
                : "Executive summary covering risk overview, business impact, and prioritized remediation roadmap."
              }
            </p>

            {/* Download */}
            <Button
              variant="primary"
              full
              onClick={() => window.open(r.fileUrl, "_blank")}
            >
              Download PDF →
            </Button>
          </Card>
        ))}
      </div>

      {/* Info box */}
      <div className="
        mt-8 border border-blue-primary/20
        bg-blue-primary/5 p-4 max-w-lg
      ">
        <p className="font-mono text-xs text-dim leading-relaxed">
          ℹ &nbsp; Reports are generated by the FashilHack team at the end
          of each engagement. You will receive an email notification when
          your report is ready.
        </p>
      </div>

    </PortalLayout>
  )
}